apiVersion: v1
kind: Pod
metadata:
  name: pod-with-annotation
  labels:
    env: myapp_v1
  annotations:
    owner: vishal
    clustertype: testenv
spec:
  containers:
    - name: cont1
      image: nginx